# Generated by Django 4.2.7 on 2023-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('receiver', 'receiver'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('client', 'client'), ('uz_standard', 'uz_standard'), ('inspector_1', 'inspector_1'), ('inspector_2', 'inspector_2'), ('client', 'client')], default='receiver', max_length=25),
        ),
    ]
