# Generated by Django 4.2.7 on 2023-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_full_name_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('receiver', 'receiver'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('client', 'client'), ('uz_standard', 'uz_standard'), ('inspector_1', 'inspector_1'), ('inspector_2', 'inspector_2')], default='receiver', max_length=25),
        ),
    ]
