# Generated by Django 4.2.7 on 2023-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('receiver', 'receiver'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('client', 'client'), ('uz_standard', 'uz_standard'), ('inspector_1', 'inspector_1'), ('inspector_2', 'inspector_2'), ('sten', 'sten')], default='receiver', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='role',
            field=models.CharField(choices=[('receiver', 'receiver'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('client', 'client'), ('uz_standard', 'uz_standard'), ('inspector_1', 'inspector_1'), ('inspector_2', 'inspector_2'), ('sten', 'sten')], default='receiver', max_length=25),
        ),
    ]
