# Generated by Django 4.2.7 on 2023-11-27 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('name_org', models.CharField(max_length=333)),
                ('created_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('received', 'received'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('payment', 'payment'), ('test', 'test'), ('docs', 'docs'), ('end', 'end')], default='received', max_length=123)),
                ('meter_brand', models.CharField(max_length=123)),
                ('serial_number', models.CharField(max_length=123)),
                ('temp_sensor', models.CharField(max_length=123)),
                ('latest_certificate', models.BooleanField(default=False)),
                ('passport_meter', models.BooleanField(default=False)),
                ('correction_block_passport', models.BooleanField(default=False)),
                ('verification_with_stamp', models.BooleanField(default=False)),
                ('gaz_pribor_stamp', models.BooleanField(default=False)),
                ('block_correction_dp', models.BooleanField(default=False)),
                ('dt', models.BooleanField(default=False)),
                ('dd', models.BooleanField(default=False)),
                ('er_300000', models.BooleanField(default=False)),
                ('visual_damage', models.BooleanField(default=False)),
                ('mechanical_damage', models.BooleanField(default=False)),
                ('conclusion', models.TextField()),
                ('indications', models.TextField()),
                ('counting_mechanism', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('ready_for_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
                ('number_hash', models.CharField(max_length=123)),
                ('count', models.PositiveIntegerField(default=0)),
                ('come_time', models.CharField(max_length=123)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderClientProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='main.orderclient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='main.orderclient')),
            ],
        ),
    ]
