# Generated by Django 4.2.7 on 2023-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclient',
            name='inspector_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='inspector_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='level_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
