# Generated by Django 4.2.7 on 2023-11-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderclient_inspector_1_orderclient_inspector_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_1', models.FileField(upload_to='uz_standard/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='uz_standard/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='uz_standard/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uaz_standard_files', to='main.orderclient')),
            ],
        ),
    ]
