# Generated by Django 4.2.7 on 2023-12-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uzstandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('payment', 'payment'), ('specialist_2', 'specialist_2'), ('test', 'test'), ('docs', 'docs'), ('end', 'end')], default='received', max_length=123),
        ),
        migrations.AlterField(
            model_name='orderclientproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='main.product'),
        ),
    ]
