# Generated by Django 4.2.7 on 2023-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderclient_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderclient',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('specialist', 'specialist'), ('accountant', 'accountant'), ('payment', 'payment'), ('specialist_2', 'specialist_2'), ('inspector_1', 'inspector_1'), ('test', 'test'), ('docs', 'docs'), ('end', 'end')], default='received', max_length=123),
        ),
    ]
