# Generated by Django 4.2.7 on 2023-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderclient_options_alter_orderclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclient',
            name='inn',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
